### ISSUE TITLE
Update to Linux Kernel 4.4?

### ISSUE THREAD

**Issue by XorgMC** [tobiasjakobi/linux-odroid-public#1]
As GitHub has no private message system, I do it this way... Are you going to update this to linux kernel 4.4?

**Comment by tobiasjakobi** [comment]
Eventually yes, also see [url=http://forum.odroid.com/viewtopic.php?f=55&t=3691&start=250#p122768]this thread[/url].

**Comment by XorgMC** [comment]
For me, the last Version (U-Boot 2015.10) from upstream works fine, althrough i cannot debug at all as i dont have a USB/UART cable. See http://i.imgur.com/kbn3uvu.jpg
(If i got the short overview of that post wrong, its late :#)
