### ISSUE TITLE
Problem with start archlinux on my old kernel

### ISSUE THREAD

**Issue by DienoX** [tobiasjakobi/linux-odroid-public#2]
Hi,
I have problem with Samsung Galaxy S3 I9300 (Exynos 4412). My device have broken screen and is not useless. I use on my android device chroot actually Ubuntu 15.10 bcs newer version does not support defeault kernel 3.0 on my device. I want to use my loved arch but arch want newest kernel.

Your kernel version might work after a slight modified on SGS3?
You could help me? Thanks a lot

**Comment by tobiasjakobi** [comment]
See README-ODROID for the intended device usage.
