### ISSUE TITLE
Arch Linux packages

### ISSUE THREAD

**Issue by frol** [tobiasjakobi/linux-odroid-public#3]
*It is not something I expect, but I would still like to make sure I don't miss a shortcut.*

To the best of your knowledge, are there Arch Linux packages (or AUR) for this kernel and/or u-boot? Where can I find the latest build/deploy instructions?

Thank you for your work!

**Comment by tobiasjakobi** [comment]
Hello,

my build instructions for the X2 can be found here:
http://linux-exynos.org/wiki/Hardkernel_ODROID-X2

These instructions should be easily adapted to the U2/U3 (some more kernel options like CONFIG_SENSORS_PWM_FAN might be necessary to enable fan operation).

- Tobias

**Comment by frol** [comment]
I don't have a fan on my U3, so it should be fine without this option, but thanks for making a note. I will try to make Arch Linux packages on the weekend and keep you posted.

**Comment by tobiasjakobi** [comment]
Be aware that this tree is not intended for 'endusers'. It's primarily meant for developers working on the Exynos4412 platform or the corresponding Odroid board series.

**Comment by frol** [comment]
Hmm, but it looks like everything is working fine, isn't it?

Currently, I experience weird issues with Mali on my Arch Linux powered U3 running 3.8.13.28-1-ARCH kernel:

1. `startx` runs, but reports the following:

    ```
gbm: failed to open any driver (search paths /usr/lib/xorg/modules/dri)
gbm: Last dlopen error: /usr/lib/xorg/modules/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
```

    I even can run `glxgears` which reports 171 FPS.
2. Kodi and Plex fail to start reporting things like this:

    ```
ERROR in Mali driver:
 * Mali device driver failed the API version check
 * The solution is probably to rebuild the libraries and the Mali device driver.
```

Thus, I thought that I would anyway like to have a more recent kernel... Do you think I would better try to backport something from Ubuntu packaging?

**Comment by tobiasjakobi** [comment]
Sorry, I can't help you with that. I use neither the vendor kernel (which Arch apparantly packages with the default image) nor Kodi or Plex.

In any case, I think the initial question was answered, so closing this.
