### ISSUE TITLE
Installation on eMMC

### ISSUE THREAD

**Issue by frol** [tobiasjakobi/linux-odroid-public#4]
Could you, please, elaborate more on the differences between SD card and eMMC installations.

I have Odroid U3 and neither [Odroid U2](http://linux-exynos.org/wiki/Hardkernel_ODROID-U2) nor [X2](http://linux-exynos.org/wiki/Hardkernel_ODROID-X2) wiki pages look complete to me, and since I don't know how would I recover my eMMC from a broken state, I would like to make sure it won't break before I do reboot...

**Comment by tobiasjakobi** [comment]
I don't boot from eMMC, so no idea.
